export const theme = {
  colors: {
    primary: '#0000CC',
    primaryHover: '#0000AA',
    secondary: '#00857C',
    white: '#FFFFFF',
    black: '#000000',
    darkText: '#1A1A1A',
    bodyText: '#444444',
    lightGrey: '#F5F5F5',
    midGrey: '#E0E0E0',
    borderGrey: '#DDDDDD',
    hcpDark: '#1A1A2E',
    warning: '#856404',
    warningBg: '#fff3cd',
    warningBorder: '#ffc107',
    danger: '#c0392b',
    dangerBg: '#fff3f3',
  },
  fonts: {
    heading: 'Georgia, "Times New Roman", serif',
    body: 'system-ui, -apple-system, Arial, sans-serif',
  },
  fontSizes: {
    xs: '0.75rem',
    sm: '0.85rem',
    base: '1rem',
    md: '1.1rem',
    lg: '1.3rem',
    xl: '1.5rem',
    xxl: '2rem',
    xxxl: '2.5rem',
    hero: '3rem',
  },
  spacing: {
    xs: '8px',
    sm: '16px',
    md: '24px',
    lg: '40px',
    xl: '60px',
    xxl: '80px',
    section: '100px',
  },
  borderRadius: {
    sm: '4px',
    md: '8px',
    lg: '16px',
    pill: '50px',
  },
  shadows: {
    sm: '0 1px 4px rgba(0,0,0,0.06)',
    md: '0 2px 12px rgba(0,0,0,0.08)',
    lg: '0 4px 24px rgba(0,0,0,0.10)',
  },
  buttons: {
    primary: {
      background: '#0000CC',
      color: '#FFFFFF',
      padding: '12px 28px',
      borderRadius: '50px',
      border: 'none',
      fontWeight: 'bold',
      fontSize: '0.95rem',
      textDecoration: 'none',
      display: 'inline-block',
      cursor: 'pointer',
    },
    outline: {
      background: 'transparent',
      color: '#0000CC',
      padding: '12px 28px',
      borderRadius: '50px',
      border: '2px solid #0000CC',
      fontWeight: 'bold',
      fontSize: '0.95rem',
      textDecoration: 'none',
      display: 'inline-block',
      cursor: 'pointer',
    },
    white: {
      background: '#FFFFFF',
      color: '#0000CC',
      padding: '12px 28px',
      borderRadius: '50px',
      border: 'none',
      fontWeight: 'bold',
      fontSize: '0.95rem',
      textDecoration: 'none',
      display: 'inline-block',
      cursor: 'pointer',
    },
    outlineWhite: {
      background: 'transparent',
      color: '#FFFFFF',
      padding: '12px 28px',
      borderRadius: '50px',
      border: '2px solid #FFFFFF',
      fontWeight: 'bold',
      fontSize: '0.95rem',
      textDecoration: 'none',
      display: 'inline-block',
      cursor: 'pointer',
    },
  },
  nav: {
    height: '70px',
    background: '#FFFFFF',
    borderBottom: '1px solid #E0E0E0',
    linkColor: '#1A1A1A',
    linkSize: '0.95rem',
  },
  sections: {
    white: { background: '#FFFFFF', padding: '100px 40px' },
    grey: { background: '#F5F5F5', padding: '100px 40px' },
    dark: { background: '#1A1A2E', padding: '100px 40px', color: '#FFFFFF' },
    blue: { background: '#0000CC', padding: '100px 40px', color: '#FFFFFF' },
  },
  maxWidth: '1200px',
}

export type Theme = typeof theme